### ISSUE TITLE
in Safari only: webpack error: new.target can't come after a prefix operator.

### ISSUE THREAD

**Issue by timbl** [linkeddata/mashlib#6]
Loading https://timbl.com/timbl/Public/ in safari, blank screen, console error:

- SyntaxError: new.target can't come after a prefix operator.

webpack parser source line:

https://github.com/WebKit/webkit/blob/master/Source/JavaScriptCore/parser/Parser.cpp#L4908

an error:

This in turn seems to be objecting to a line "if (!new.target)"  in a URL library:

```
const conversions = __webpack_require__(237);
const utils = __webpack_require__(240);
const impl = utils.implSymbol;

function URL(url) {
  if (!new.target) {
    throw new TypeError(
      "Failed to construct 'URL'. Please use the 'new' operator; this constructor cannot be called as a function."
    );
  }
  if (arguments.length < 1) {
    throw new TypeError("Failed to construct 'URL': 1 argument required, but only " + arguments.length + " present.");
  }
```

**Comment by RubenVerborgh** [comment]
@timbl Where did you find that code? I've just checked out mashlib, and built a new version, but neither `grep 'new.target' dist/*` nor `grep -l 'whatwg-url' dist/*` shows anything.

This is expected, since webpack replaces `whatwg-url` with `window`.

**Comment by AnthonyTwoBears** [comment]
This is a safari bug. The latest tech preview fixes it. Very weird.

The code above comes from jsdom package in the events.js file.

see  https://github.com/jsdom/webidl2js/issues/78

**Comment by timbl** [comment]
I'll close this as a mashlib issue then.
